
language: python
python:
 - "3.5"

install:
 - pip install coverage


script: 
 - make test
 - coverage run -m unittest discover

after_success:
 COVERALLS_REPO_TOKEN=F8lr6O2tqMK7lW59AQEjQKrBLZTvkrak9


